-   repo: local
    hooks:
    -   id: trailing-whitespace-fixer
        name: trailing-whitespace-fixer
        description: trailing-whitespace-fixer
        entry: trailing-whitespace-fixer
        language: python
        types: [text]
    -   id: end-of-file-fixer
        name: end-of-file-fixer
        description: "Makes sure files end in a newline and only a newline"
        entry: end-of-file-fixer
        language: python
        types: [text]
    -   id: add-trailing-comma
        name: add-trailing-comma
        description: add-trailing-comma
        entry: add-trailing-comma
        language: system
        types: [python]
    -   id: black
        name: black
        description: "Black: The uncompromising Python code formatter"
        entry: black
        language: system
        types: [python]
